// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjHH6eluKXYZz79rXSsvQLI8XO1NlxLcE',
    appId: '1:586377945755:web:430ee083fb5a929b17dc3e',
    messagingSenderId: '586377945755',
    projectId: 'artefak-io',
    authDomain: 'artefak-io.firebaseapp.com',
    storageBucket: 'artefak-io.appspot.com',
    measurementId: 'G-FDFC2E0QG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQr__6DQ0CAFKQU69VsY0OxJG8laYFH24',
    appId: '1:586377945755:android:74b06575ff9e90e317dc3e',
    messagingSenderId: '586377945755',
    projectId: 'artefak-io',
    storageBucket: 'artefak-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSW5YLIapIYa0_o41Z_jZ7IWRZp0eNEVk',
    appId: '1:586377945755:ios:af6c407dc2502d4f17dc3e',
    messagingSenderId: '586377945755',
    projectId: 'artefak-io',
    storageBucket: 'artefak-io.appspot.com',
    iosClientId: '586377945755-arikd9gqv71to4m1vac8t0lravv4h7jh.apps.googleusercontent.com',
    iosBundleId: 'io.artefak.app',
  );
}
