# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a new Beta Build"
  lane :beta do
    gradle(task: "clean bundleRelease")
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    versions = google_play_track_version_codes(track: "alpha")
    version_code = versions[0]

    # gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: "alpha",
      version_code: version_code
    )
  end
end
